[2024-05-16 12:59:35,450] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: keypoints_dag.preprocess_data scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16 12:59:35,453] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: keypoints_dag.preprocess_data scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16 12:59:35,453] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-16 12:59:35,453] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-05-16 12:59:35,453] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-16 12:59:35,457] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-05-15 00:00:00+00:00
[2024-05-16 12:59:35,466] {standard_task_runner.py:52} INFO - Started process 91177 to run task
[2024-05-16 12:59:35,470] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'keypoints_dag', 'preprocess_data', 'scheduled__2024-05-15T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_airflow.py', '--cfg-path', '/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/tmptw0_0cvr', '--error-file', '/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/tmp244rg4g7']
[2024-05-16 12:59:35,471] {standard_task_runner.py:77} INFO - Job 3: Subtask preprocess_data
[2024-05-16 12:59:35,492] {logging_mixin.py:109} INFO - Running <TaskInstance: keypoints_dag.preprocess_data scheduled__2024-05-15T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2024-05-16 12:59:35,507] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=keypoints_dag
AIRFLOW_CTX_TASK_ID=preprocess_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-15T00:00:00+00:00
[2024-05-16 12:59:35,511] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-05-16 12:59:35,511] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2024-05-16 12:59:35,512] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2024-05-16 12:59:35,512] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-05-16 12:59:35,513] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 12:59:35,513] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 12:59:35,514] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2024-05-16 12:59:35,514] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-05-16 12:59:35,515] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 12:59:35,515] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 12:59:35,516] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 12:59:35,516] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 12:59:35,521] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nikhilanand/BigDataLabProject/dags/preprocess_airflow.py", line 17, in _preprocess_data
    train = pd.read_csv("training.csv")
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'training.csv'
[2024-05-16 12:59:35,526] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=keypoints_dag, task_id=preprocess_data, execution_date=20240515T000000, start_date=20240516T072935, end_date=20240516T072935
[2024-05-16 12:59:35,530] {standard_task_runner.py:89} ERROR - Failed to execute job 3 for task preprocess_data
Traceback (most recent call last):
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nikhilanand/BigDataLabProject/dags/preprocess_airflow.py", line 17, in _preprocess_data
    train = pd.read_csv("training.csv")
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'training.csv'
[2024-05-16 12:59:35,578] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-16 12:59:35,589] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16 13:05:07,611] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: keypoints_dag.preprocess_data scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16 13:05:07,614] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: keypoints_dag.preprocess_data scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16 13:05:07,614] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-16 13:05:07,614] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-05-16 13:05:07,614] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-16 13:05:07,618] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-05-15 00:00:00+00:00
[2024-05-16 13:05:07,627] {standard_task_runner.py:52} INFO - Started process 95399 to run task
[2024-05-16 13:05:07,631] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'keypoints_dag', 'preprocess_data', 'scheduled__2024-05-15T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_airflow.py', '--cfg-path', '/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/tmp3id5hf7h', '--error-file', '/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/tmpfh0hrjfq']
[2024-05-16 13:05:07,632] {standard_task_runner.py:77} INFO - Job 3: Subtask preprocess_data
[2024-05-16 13:05:07,653] {logging_mixin.py:109} INFO - Running <TaskInstance: keypoints_dag.preprocess_data scheduled__2024-05-15T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2024-05-16 13:05:07,670] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=keypoints_dag
AIRFLOW_CTX_TASK_ID=preprocess_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-15T00:00:00+00:00
[2024-05-16 13:05:07,674] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-05-16 13:05:07,674] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2024-05-16 13:05:07,675] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2024-05-16 13:05:07,675] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-05-16 13:05:07,676] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:05:07,676] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:05:07,677] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:05:07,677] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-05-16 13:05:07,678] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:05:07,678] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:05:07,679] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:05:07,679] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:05:07,684] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nikhilanand/BigDataLabProject/dags/preprocess_airflow.py", line 17, in _preprocess_data
    train = pd.read_csv("training.csv")
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'training.csv'
[2024-05-16 13:05:07,690] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=keypoints_dag, task_id=preprocess_data, execution_date=20240515T000000, start_date=20240516T073507, end_date=20240516T073507
[2024-05-16 13:05:07,694] {standard_task_runner.py:89} ERROR - Failed to execute job 3 for task preprocess_data
Traceback (most recent call last):
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nikhilanand/BigDataLabProject/dags/preprocess_airflow.py", line 17, in _preprocess_data
    train = pd.read_csv("training.csv")
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'training.csv'
[2024-05-16 13:05:07,740] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-16 13:05:07,750] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
