[2024-05-16 13:07:35,436] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: keypoints_dag.preprocess_data manual__2024-05-16T07:37:25.386356+00:00 [queued]>
[2024-05-16 13:07:35,438] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: keypoints_dag.preprocess_data manual__2024-05-16T07:37:25.386356+00:00 [queued]>
[2024-05-16 13:07:35,439] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-16 13:07:35,439] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-05-16 13:07:35,439] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-16 13:07:35,442] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-05-16 07:37:25.386356+00:00
[2024-05-16 13:07:35,451] {standard_task_runner.py:52} INFO - Started process 97121 to run task
[2024-05-16 13:07:35,455] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'keypoints_dag', 'preprocess_data', 'manual__2024-05-16T07:37:25.386356+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_airflow.py', '--cfg-path', '/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/tmpbcgh25lc', '--error-file', '/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/tmpouen1jnc']
[2024-05-16 13:07:35,457] {standard_task_runner.py:77} INFO - Job 5: Subtask preprocess_data
[2024-05-16 13:07:35,476] {logging_mixin.py:109} INFO - Running <TaskInstance: keypoints_dag.preprocess_data manual__2024-05-16T07:37:25.386356+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2024-05-16 13:07:35,489] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=keypoints_dag
AIRFLOW_CTX_TASK_ID=preprocess_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-16T07:37:25.386356+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-16T07:37:25.386356+00:00
[2024-05-16 13:07:35,493] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-05-16 13:07:35,494] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2024-05-16 13:07:35,494] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2024-05-16 13:07:35,495] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-05-16 13:07:35,495] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:07:35,496] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:07:35,496] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:07:35,496] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-05-16 13:07:35,497] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:07:35,497] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:07:35,498] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:07:35,498] {logging_mixin.py:109} WARNING - /Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-05-16 13:07:35,504] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nikhilanand/BigDataLabProject/dags/preprocess_airflow.py", line 18, in _preprocess_data
    train = pd.read_csv(data_path+"/training.csv")
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 574, in pandas._libs.parsers.TextReader.__cinit__
  File "parsers.pyx", line 663, in pandas._libs.parsers.TextReader._get_header
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2053, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 18: invalid start byte
[2024-05-16 13:07:35,510] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=keypoints_dag, task_id=preprocess_data, execution_date=20240516T073725, start_date=20240516T073735, end_date=20240516T073735
[2024-05-16 13:07:35,514] {standard_task_runner.py:89} ERROR - Failed to execute job 5 for task preprocess_data
Traceback (most recent call last):
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nikhilanand/BigDataLabProject/dags/preprocess_airflow.py", line 18, in _preprocess_data
    train = pd.read_csv(data_path+"/training.csv")
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/Users/nikhilanand/airflow_venv/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 574, in pandas._libs.parsers.TextReader.__cinit__
  File "parsers.pyx", line 663, in pandas._libs.parsers.TextReader._get_header
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2053, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 18: invalid start byte
[2024-05-16 13:07:35,563] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-16 13:07:35,573] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
